<?php
/**
 * Custom Gutenberg Blocks Registration
 *
 * Registers custom blocks using the blocks-manifest.php file generated by wp-scripts.
 * Supports WordPress 6.7+ optimized registration APIs.
 *
 * @package SmallFishBusiness
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers custom Gutenberg blocks.
 *
 * Uses the most efficient registration method available based on WordPress version:
 * - WordPress 6.8+: wp_register_block_types_from_metadata_collection()
 * - WordPress 6.7: wp_register_block_metadata_collection() + individual registration
 * - Earlier versions: Individual register_block_type() calls
 *
 * @see https://make.wordpress.org/core/2025/03/13/more-efficient-block-type-registration-in-6-8/
 * @see https://make.wordpress.org/core/2024/10/17/new-block-type-registration-apis-to-improve-performance-in-wordpress-6-7/
 */
function sfb_register_blocks() {
	$blocks_dir    = get_template_directory() . '/blocks';
	$manifest_path = get_template_directory() . '/blocks/blocks-manifest.php';

	// Check if blocks directory exists.
	if ( ! is_dir( $blocks_dir ) || ! file_exists( $manifest_path ) ) {
		return;
	}

	/**
	 * WordPress 6.8+ - Most efficient method.
	 * Registers block types directly from metadata collection.
	 */
	if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) ) {
		wp_register_block_types_from_metadata_collection( $blocks_dir, $manifest_path );
		return;
	}

	/**
	 * WordPress 6.7 - Register metadata collection for performance.
	 */
	if ( function_exists( 'wp_register_block_metadata_collection' ) ) {
		wp_register_block_metadata_collection( $blocks_dir, $manifest_path );
	}

	/**
	 * Register each block type individually.
	 * Required for WordPress < 6.8 or as fallback.
	 */
	$manifest_data = require $manifest_path;
	foreach ( array_keys( $manifest_data ) as $block_type ) {
		register_block_type( $blocks_dir . '/' . $block_type );
	}
}
add_action( 'init', 'sfb_register_blocks' );
